using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace llmap
{
    static class AirportSites
    {
        public static List<AirportSite> Data = new List<AirportSite>()
        {
            new AirportSite {Code = "YEG", City = "Edmonton", State = "AB", FullSiteName = "AIRPORT_YEG_Edmonton International Airport", Latitude = 53.3097, Longitude = -113.58},
        new AirportSite {Code = "YYC", City = "Calgary", State = "AB", FullSiteName = "AIRPORT_YYC_Calgary International Airport", Latitude = 51.1341, Longitude = -114.007},
        new AirportSite {Code = "ANC", City = "Anchorage", State = "AK", FullSiteName = "AIRPORT_ANC_Ted Stevens Anchorage International", Latitude = 61.1744, Longitude = -149.996},
        new AirportSite {Code = "BHM", City = "Birmingham", State = "AL", FullSiteName = "AIRPORT_BHM_Birmingham-Shuttlesworth International Airport", Latitude = 33.5606, Longitude = -86.7493},
        new AirportSite {Code = "HSV", City = "Huntsville", State = "AL", FullSiteName = "AIRPORT_HSV_Huntsville International Airport", Latitude = 34.6495, Longitude = -86.7762},
        new AirportSite {Code = "LIT", City = "Little Rock", State = "AR", FullSiteName = "AIRPORT_LIT_Bill and Hillary Clinton National Airport", Latitude = 34.7276, Longitude = -92.2209},
        new AirportSite {Code = "PHX", City = "Phoenix", State = "AZ", FullSiteName = "AIRPORT_PHX_Phoenix Sky Harbor International Airport", Latitude = 33.4377, Longitude = -112.031},
        new AirportSite {Code = "SAN", City = "San Diego", State = "CA", FullSiteName = "AIRPORT_SAN_San Diego International Airport", Latitude = 32.7299, Longitude = -117.196},
        new AirportSite {Code = "LGB", City = "Long Beach", State = "CA", FullSiteName = "AIRPORT_LGB_Long Beach Airport", Latitude = 33.8187, Longitude = -118.144},
        new AirportSite {Code = "MHR", City = "Sacramento", State = "CA", FullSiteName = "AIRPORT_MHR_Sacramento Mather Airport", Latitude = 38.5667, Longitude = -121.297},
        new AirportSite {Code = "OAK", City = "Oakland", State = "CA", FullSiteName = "AIRPORT_OAK_Oakland International Airport", Latitude = 37.7126, Longitude = -122.213},
        new AirportSite {Code = "ONT", City = "Ontario", State = "CA", FullSiteName = "AIRPORT_ONT_LA Ontario International Airport", Latitude = 34.0622, Longitude = -117.595},
        new AirportSite {Code = "FAT", City = "Fresno", State = "CA", FullSiteName = "AIRPORT_FAT_Fresno Yosemite International Airport", Latitude = 36.7678, Longitude = -119.717},
        new AirportSite {Code = "LAX", City = "Los Angeles", State = "CA", FullSiteName = "AIRPORT_LAX_Los Angeles International", Latitude = 33.9425, Longitude = -118.407},
        new AirportSite {Code = "SJC", City = "San Jose", State = "CA", FullSiteName = "AIRPORT_SJC_Norman Y Mineta San Jose International Airport", Latitude = 37.3577, Longitude = -121.931},
        new AirportSite {Code = "DEN", City = "Denver", State = "CO", FullSiteName = "AIRPORT_DEN_Denver International Airport", Latitude = 39.8384, Longitude = -104.672},
        new AirportSite {Code = "FLL", City = "Fort Lauderdale", State = "FL", FullSiteName = "AIRPORT_FLL_Fort Lauderdale–Hollywood International Airport", Latitude = 26.0715, Longitude = -80.1329},
        new AirportSite {Code = "JAX", City = "Jacksonville", State = "FL", FullSiteName = "AIRPORT_JAX_Jacksonville International Airport", Latitude = 30.4916, Longitude = -81.6765},
        new AirportSite {Code = "MCO", City = "Orlando", State = "FL", FullSiteName = "AIRPORT_MCO_Orlando International Airport", Latitude = 28.4395, Longitude = -81.3114},
        new AirportSite {Code = "RSW", City = "Fort Myers", State = "FL", FullSiteName = "AIRPORT_RSW_Southwest Florida International Airport", Latitude = 26.5232, Longitude = -81.7547},
        new AirportSite {Code = "PIE", City = "Clearwater", State = "FL", FullSiteName = "AIRPORT_PIE_St Petersburg–Clearwater International Airport", Latitude = 27.9065, Longitude = -82.6911},
        new AirportSite {Code = "PNS", City = "Pensacola", State = "FL", FullSiteName = "AIRPORT_PNS_Pensacola International Airport", Latitude = 30.4757, Longitude = -87.1945},
        new AirportSite {Code = "PBI", City = "West Palm Beach", State = "FL", FullSiteName = "AIRPORT_PBI_Palm Beach International Airport", Latitude = 26.6908, Longitude = -80.0876},
        new AirportSite {Code = "MIA", City = "Miami", State = "FL", FullSiteName = "AIRPORT_MIA_Miami International", Latitude = 25.7833, Longitude = -80.2667},
        new AirportSite {Code = "ABY", City = "Albany", State = "GA", FullSiteName = "AIRPORT_ABY_Southwest Georgia Regional Airport", Latitude = 31.5324, Longitude = -84.188},
        new AirportSite {Code = "ATL", City = "Atlanta", State = "GA", FullSiteName = "AIRPORT_ATL_Hartsfield-Jackson Atlanta International Airport", Latitude = 33.6408, Longitude = -84.4499},
        new AirportSite {Code = "KOA", City = "Kona", State = "HI", FullSiteName = "AIRPORT_KOA_Kona International Airport", Latitude = 19.7333, Longitude = -156.038},
        new AirportSite {Code = "HNL", City = "Honolulu", State = "HI", FullSiteName = "AIRPORT_HNL_Honolulu International Airport", Latitude = 21.3354, Longitude = -157.919},
        new AirportSite {Code = "OGG", City = "Maui", State = "HI", FullSiteName = "AIRPORT_OGG_Kahului Airport", Latitude = 20.8933, Longitude = -156.443},
        new AirportSite {Code = "DSM", City = "Des Moines", State = "IA", FullSiteName = "AIRPORT_DSM_Des Moines International Airport", Latitude = 41.5334, Longitude = -93.6481},
        new AirportSite {Code = "CID", City = "Cedar Rapids", State = "IA", FullSiteName = "AIRPORT_CID_The Eastern Iowa Airport", Latitude = 41.8895, Longitude = -91.7003},
        new AirportSite {Code = "BOI", City = "Boise", State = "ID", FullSiteName = "AIRPORT_BOI_Boise Airport", Latitude = 43.5709, Longitude = -116.222},
        new AirportSite {Code = "RFD", City = "Rockford", State = "IL", FullSiteName = "AIRPORT_RFD_Chicago Rockford International Airport", Latitude = 42.2019, Longitude = -89.0958},
        new AirportSite {Code = "ORD", City = "Chicago, Il", State = "IL", FullSiteName = "AIRPORT_ORD_Chicago O'Hare International", Latitude = 41.9786, Longitude = -87.9047},
        new AirportSite {Code = "IND", City = "Indianapolis, IN", State = "IN", FullSiteName = "AIRPORT_IND_Indianapolis International", Latitude = 39.7172, Longitude = -86.2947},
        new AirportSite {Code = "SBN", City = "South Bend", State = "IN", FullSiteName = "AIRPORT_SBN_San Antonio International Airport", Latitude = 41.7005, Longitude = -86.3108},
        new AirportSite {Code = "FWA", City = "Fort Wayne", State = "IN", FullSiteName = "AIRPORT_FWA_Fort Wayne International Airport", Latitude = 40.9893, Longitude = -85.191},
        new AirportSite {Code = "ICT", City = "Wichita", State = "KS", FullSiteName = "AIRPORT_ICT_Wichita Mid-Continent Airport ", Latitude = 37.6536, Longitude = -97.4302},
        new AirportSite {Code = "CVG", City = "Covington", State = "KY", FullSiteName = "AIRPORT_CVG_Cincinnati Northern Kentucky International Airport", Latitude = 39.0577, Longitude = -84.6628},
        new AirportSite {Code = "SDF", City = "Louisville, KY", State = "KY", FullSiteName = "AIRPORT_SDF_Louisville International (Standiford Field)", Latitude = 38.1744, Longitude = -85.7361},
        new AirportSite {Code = "SHV", City = "Shreveport", State = "LA", FullSiteName = "AIRPORT_SHV_Shreveport Regional Airport", Latitude = 32.4551, Longitude = -93.8259},
        new AirportSite {Code = "MSY", City = "New Orleans", State = "LA", FullSiteName = "AIRPORT_MSY_Louis Armstrong New Orleans International Airport", Latitude = 29.983, Longitude = -90.257},
        new AirportSite {Code = "LFT", City = "Lafayette", State = "LA", FullSiteName = "AIRPORT_LFT_Lafayette Regional Airport", Latitude = 30.2083, Longitude = -91.9933},
        new AirportSite {Code = "LAN", City = "Lansing", State = "MI", FullSiteName = "AIRPORT_LAN_Capital Region International Airport", Latitude = 42.7749, Longitude = -84.5895},
        new AirportSite {Code = "DTW", City = "Detroit", State = "MI", FullSiteName = "AIRPORT_DTW_Detroit Metropolitan Wayne County Airport", Latitude = 42.2294, Longitude = -83.3433},
        new AirportSite {Code = "MSP", City = "Minneapolis", State = "MN", FullSiteName = "AIRPORT_MSP_Minneapolis–Saint Paul International Airport", Latitude = 44.881, Longitude = -93.2007},
        new AirportSite {Code = "MCI", City = "Kansas City", State = "MO", FullSiteName = "AIRPORT_MCI_Kansas City International Airport", Latitude = 39.3001, Longitude = -94.7181},
        new AirportSite {Code = "SGF", City = "Springfield", State = "MO", FullSiteName = "AIRPORT_SGF_Springfield-Branson National Airport", Latitude = 37.2384, Longitude = -93.3963},
        new AirportSite {Code = "STL", City = "St Louis", State = "MO", FullSiteName = "AIRPORT_STL_Lambert–St. Louis International Airport", Latitude = 38.7409, Longitude = -90.364},
        new AirportSite {Code = "JAN", City = "Jackson", State = "MS", FullSiteName = "AIRPORT_JAN_Jackson-Evers International Airport", Latitude = 32.3084, Longitude = -90.0736},
        new AirportSite {Code = "BIL", City = "Billings", State = "MT", FullSiteName = "AIRPORT_BIL_Billings Logan International Airport", Latitude = 45.8035, Longitude = -108.538},
        new AirportSite {Code = "CLT", City = "Charlotte", State = "NC", FullSiteName = "AIRPORT_CLT_Charlotte Douglas International Airport", Latitude = 35.2227, Longitude = -80.9463},
        new AirportSite {Code = "GSO", City = "Greensboro", State = "NC", FullSiteName = "AIRPORT_GSO_Piedmont Triad International Airport", Latitude = 36.1038, Longitude = -79.9427},
        new AirportSite {Code = "RDU", City = "Raleigh/Durham", State = "NC", FullSiteName = "AIRPORT_RDU_Raleigh–Durham International Airport", Latitude = 35.8727, Longitude = -78.7954},
        new AirportSite {Code = "OMA", City = "Omaha", State = "NE", FullSiteName = "AIRPORT_OMA_Eppley Airfield", Latitude = 41.3, Longitude = -95.9},
        new AirportSite {Code = "ABQ", City = "Albuquerque", State = "NM", FullSiteName = "AIRPORT_ABQ_Albuquerque International Sunport", Latitude = 35.0495, Longitude = -106.623},
        new AirportSite {Code = "LAS", City = "Las Vegas", State = "NV", FullSiteName = "AIRPORT_LAS_McCarran International Airport", Latitude = 36.0813, Longitude = -115.143},
        new AirportSite {Code = "RNO", City = "Reno", State = "NV", FullSiteName = "AIRPORT_RNO_Reno–Tahoe International Airport", Latitude = 39.5066, Longitude = -119.775},
        new AirportSite {Code = "LCK", City = "Columbus", State = "OH", FullSiteName = "AIRPORT_LCK_Rickenbacker International Airport", Latitude = 39.9974, Longitude = -82.8877},
        new AirportSite {Code = "CLE", City = "Cleveland", State = "OH", FullSiteName = "AIRPORT_CLE_Cleveland Hopkins International Airport", Latitude = 41.4118, Longitude = -81.8346},
        new AirportSite {Code = "DAY", City = "Dayton", State = "OH", FullSiteName = "AIRPORT_DAY_James M Cox Dayton International Airport", Latitude = 39.8983, Longitude = -84.2215},
        new AirportSite {Code = "OKC", City = "Oklahoma City", State = "OK", FullSiteName = "AIRPORT_OKC_Will Rogers World Airport", Latitude = 35.3982, Longitude = -97.5975},
        new AirportSite {Code = "TUL", City = "Tulsa", State = "OK", FullSiteName = "AIRPORT_TUL_Tulsa International Airport", Latitude = 36.1883, Longitude = -95.8892},
        new AirportSite {Code = "YHM", City = "Hamilton", State = "ON", FullSiteName = "AIRPORT_YHM_John C Munro Hamilton International Airport", Latitude = 43.1634, Longitude = -79.9262},
        new AirportSite {Code = "YYZ", City = "Toronto", State = "ON", FullSiteName = "AIRPORT_YYZ_Toronto Pearson International Airport", Latitude = 43.6851, Longitude = -79.6151},
        new AirportSite {Code = "PDX", City = "Portland", State = "OR", FullSiteName = "AIRPORT_PDX_Portland International Airport", Latitude = 45.5892, Longitude = -122.593},
        new AirportSite {Code = "YMX", City = "Montreal", State = "PQ", FullSiteName = "AIRPORT_YMX_Montreal–Mirabel International Airport", Latitude = 45.6763, Longitude = -74.0395},
        new AirportSite {Code = "YOW", City = "Ottawa", State = "PQ", FullSiteName = "AIRPORT_YOW_Ottawa Macdonald-Cartier International Airport", Latitude = 45.3267, Longitude = -75.6584},
        new AirportSite {Code = "YUL", City = "Montreal", State = "PQ", FullSiteName = "AIRPORT_YUL_Montreal–Pierre Elliott Trudeau International Airport ", Latitude = 45.4562, Longitude = -73.7458},
        new AirportSite {Code = "CAE", City = "Columbia", State = "SC", FullSiteName = "AIRPORT_CAE_Columbia Metropolitan Airport", Latitude = 33.9434, Longitude = -81.1168},
        new AirportSite {Code = "GSP", City = "Greenville", State = "SC", FullSiteName = "AIRPORT_GSP_Greenville-Spartanburg International Airport", Latitude = 34.8907, Longitude = -82.2169},
        new AirportSite {Code = "FSD", City = "Sioux Falls", State = "SD", FullSiteName = "AIRPORT_FSD_Sioux Falls Regional Airport", Latitude = 43.5819, Longitude = -96.7434},
        new AirportSite {Code = "BNA", City = "Nashville", State = "TN", FullSiteName = "AIRPORT_BNA_Nashville International Airport", Latitude = 36.1344, Longitude = -86.6681},
        new AirportSite {Code = "TYS", City = "Knoxville", State = "TN", FullSiteName = "AIRPORT_TYS_McGhee Tyson Airport", Latitude = 35.8066, Longitude = -83.9888},
        new AirportSite {Code = "MEM", City = "Memphis", State = "TN", FullSiteName = "AIRPORT_MEM_Memphis International", Latitude = 35.0667, Longitude = -89.9667},
        new AirportSite {Code = "AUS", City = "Austin", State = "TX", FullSiteName = "AIRPORT_AUS_Austin-Bergstrom International Airport", Latitude = 30.2026, Longitude = -97.6655},
        new AirportSite {Code = "DFW", City = "Dallas", State = "TX", FullSiteName = "AIRPORT_DFW_Dallas Fort Worth International Airport", Latitude = 32.8663, Longitude = -97.0398},
        new AirportSite {Code = "ELP", City = "El Paso", State = "TX", FullSiteName = "AIRPORT_ELP_El Paso International Airport", Latitude = 31.798, Longitude = -106.394},
        new AirportSite {Code = "IAH", City = "Houston", State = "TX", FullSiteName = "AIRPORT_IAH_George Bush Intercontinental Airport", Latitude = 29.9787, Longitude = -95.3414},
        new AirportSite {Code = "SAT", City = "San Antonio", State = "TX", FullSiteName = "AIRPORT_SAT_San Antonio International Airport", Latitude = 29.5255, Longitude = -98.4723},
        new AirportSite {Code = "MFE", City = "Mc Allen", State = "TX", FullSiteName = "AIRPORT_MFE_McAllen-Miller International Airport", Latitude = 26.1808, Longitude = -98.241},
        new AirportSite {Code = "LRD", City = "Laredo", State = "TX", FullSiteName = "AIRPORT_LRD_Laredo International Airport", Latitude = 27.5431, Longitude = -99.4554},
        new AirportSite {Code = "SLC", City = "Salt Lake City", State = "UT", FullSiteName = "AIRPORT_SLC_Salt Lake City International Airport", Latitude = 40.7861, Longitude = -111.98},
        new AirportSite {Code = "ORF", City = "Norfolk", State = "VA", FullSiteName = "AIRPORT_ORF_Norfolk International Airport", Latitude = 36.8984, Longitude = -76.2115},
        new AirportSite {Code = "ROA", City = "Roanoke", State = "VA", FullSiteName = "AIRPORT_ROA_oke Regional Airport", Latitude = 37.3206, Longitude = -79.9698},
        new AirportSite {Code = "RIC", City = "Richmond", State = "VA", FullSiteName = "AIRPORT_RIC_Richmond International Airport", Latitude = 37.5082, Longitude = -77.3324},
        new AirportSite {Code = "GEG", City = "Spokane", State = "WA", FullSiteName = "AIRPORT_GEG_Spokane International Airport", Latitude = 47.6251, Longitude = -117.538},
        new AirportSite {Code = "BFI", City = "Seattle", State = "WA", FullSiteName = "AIRPORT_BFI_Boeing Field International Airport", Latitude = 47.5375, Longitude = -122.304},
        new AirportSite {Code = "MKE", City = "Milwaukee", State = "WI", FullSiteName = "AIRPORT_MKE_General Mitchell International Airport", Latitude = 42.9472, Longitude = -87.9049}
        };
    }
}
